### ISSUE TITLE
Make a note in Python/README that anaconda python may cause problems if not pointing to clang v.>10.0.0

### ISSUE THREAD

**Issue by MrAE** [neurodata/SPORF#213]
@j1c 

If you find out how to get anaconda-python to point to the correct version of clang, please comment.

**Comment by MantieReid** [comment]
@MrAE 

I have made a pull request. The note was added to the readme. 

The pull request is located here in the link below.   Please, if you can, approve it. 


https://github.com/neurodata/RerF/pull/219

**Comment by falkben** [comment]
We believe this is probably inaccurate about the particular version of clang.  In any case, the fix is probably just to publish a built version to pypi for each platform/architecture and have people install it without having to build it themselves.  @MrAE feel free to re-open if you disagree.
