### ISSUE TITLE
vectorize predict_post

### ISSUE THREAD

**Issue by MrAE** [neurodata/SPORF#239]
Operating on n > 1e6 samples, the current implementation `predict_post` is slow.

**Comment by falkben** [comment]
not sure we really need to vectorize -- could just make the entire call from within the C++ extension, which should be enough

**Comment by falkben** [comment]
Is predict fast enough?  Is it just predict_post that was slow?  What prompted this issue?

**Comment by MrAE** [comment]
It was just predict_post

**Comment by MrAE** [comment]
Satish said it was quite a bit slower than the predict function

**Comment by falkben** [comment]
fixed in https://github.com/neurodata/RerF/pull/244
