### ISSUE TITLE
This line will sample 1's twice as often as -1's?

### ISSUE THREAD

**Issue by MrAE** [neurodata/SPORF#257]
@falkben @jbrowne6  
https://github.com/neurodata/RerF/blob/7c7b311c1cc65b9eb7c1da9c34df99dee17d10c5/packedForest/src/forestTypes/binnedTree/processingNodeBin.h#L96

I suggest the following fix:
```
rndWeight = (randNum->gen(1)) ? 1 : -1; 
```

**Comment by falkben** [comment]
Is mwc inclusive in it's end range? My guess is no...

**Comment by MrAE** [comment]
Yep, you’re right
